# NOTE: If you are trying to run this off of your fork, you have to change the
# docroot in travis/configuration.inc.php from /qcubed/ to the name of your fork.
language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - nightly

install:
    - composer install
    - composer require "predis/predis:^1.1"

addons:
  apt:
    packages:
      - redis-server

services:
  - redis-server

env:
    - DB=mysql
    - DB=pgsql POSTGRESQL_VERSION=9.1
    - DB=pgsql POSTGRESQL_VERSION=9.2
    - DB=pgsql POSTGRESQL_VERSION=9.3
    - DB=pgsql POSTGRESQL_VERSION=9.4

before_script:
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database qcubed;'; mysql -u root qcubed < assets/php/examples/mysql_innodb.sql; fi"
    - sh -c "if [ '$DB' = 'pgsql' ]; then createdb qcubed -U postgres; psql -d qcubed -f assets/php/examples/pgsql.sql -U postgres; fi"

script: travis/test.php

# code coverage
addons:
    code_climate:
        repo_token: 814dfe2ee0ae6198e43e566e32ab85f40379b5abe06cd52b1f6a24e92b5de883

# code coverage
after_script:
    - vendor/bin/test-reporter

sudo: false

matrix:
  include:
    # test against the latest HHVM version by using trusty
    - php: hhvm
      env: DB=mysql
      sudo: true
      dist: trusty
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      install:
          - composer install
          # No predis test here

  exclude:
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.1 # driver currently unsupported by HHVM
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.2 # driver currently unsupported by HHVM
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.3 # driver currently unsupported by HHVM
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.4 # driver currently unsupported by HHVM

